[package]
authors = ["Elliott Linder <elliott@linder.bz>"]
name = "mucs"
version = "0.1.0"
build = "build.rs"
edition = "2018"

[[bin]]
doc = false
name = "mu-cs"
path = "src/bin/main.rs"

[dependencies]
grpcio = { version = "0.4.0", default-features = false, features = ["protobuf-codec"] }
muonline-packet = { path = "../Packet/muonline-packet" }
muonline-packet_codec = { path = "../Packet/muonline-packet_codec" }
muonline-protocol = { path = "../Protocol" }
evmap = "4.0.0"
futures = "0.1.25"
protobuf = "2.0"
failure = "0.1.2"
try_from = "0.2.2"
tokio = "0.1.11"
index-pool = "1.0.11"

[build-dependencies]
protoc-grpcio = "0.2"
